
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, name TEXT NOT NULL,
 password TEXT NOT NULL, school TEXT NOT NULL, age INTEGER NOT NULL,
 coins INTEGER NOT NULL DEFAULT 0 CHECK(coins >= 0));
CREATE TABLE IF NOT EXISTS sessions (
 token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires REAL NOT NULL);
CREATE TABLE IF NOT EXISTS friendships (
 sender TEXT REFERENCES users(id) ON DELETE CASCADE,
 recipient TEXT REFERENCES users(id) ON DELETE CASCADE,
 accepted INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(sender,recipient), CHECK(sender != recipient));
CREATE TABLE IF NOT EXISTS blocks (
 owner TEXT REFERENCES users(id) ON DELETE CASCADE,
 target TEXT REFERENCES users(id) ON DELETE CASCADE, hidden INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(owner,target));
CREATE TABLE IF NOT EXISTS votes (
 id TEXT PRIMARY KEY, responder TEXT REFERENCES users(id) ON DELETE CASCADE,
 recipient TEXT REFERENCES users(id) ON DELETE CASCADE,
 poll_id TEXT NOT NULL, day TEXT NOT NULL, timestamp TEXT NOT NULL,
 is_read INTEGER NOT NULL DEFAULT 0, UNIQUE(responder,poll_id,day));
CREATE INDEX IF NOT EXISTS inbox_idx ON votes(recipient,timestamp);
CREATE TABLE IF NOT EXISTS reports (
 id TEXT PRIMARY KEY, reporter TEXT REFERENCES users(id) ON DELETE CASCADE,
 vote_id TEXT REFERENCES votes(id) ON DELETE CASCADE, reason TEXT NOT NULL,
 timestamp TEXT NOT NULL, UNIQUE(reporter,vote_id));
CREATE TABLE IF NOT EXISTS rate_limits (
 key TEXT PRIMARY KEY, start REAL NOT NULL, count INTEGER NOT NULL);
